### ISSUE TITLE
"Generally" gets split to "General ly"

### ISSUE THREAD

**Issue by CthulhuPete** [Jourhighness/dcc-spell-helper#1]
When converting a spell if the word "Generally" is encountered, splits it to "General" the a line break and "ly", this causes tables to break and cause problems if not spotted.  Here is  example of the last entry of the "Consult Spirit" spell

```
36+ ............. mind to guide his actions. 

General
ly speaking, this is sufficient.........
```

**Comment by Jourhighness** [comment]
Ive managed reproduced it myself now, i think i know the problem I will look into it.

**Comment by Jourhighness** [comment]
should be fixed now.
